# Семинар 1. Инструменты: Python, Numpy

Данный семинар будет посвящен основным инструментам анализа данных.

План ноутбука:
* Очень кратко вспомнить азы Python и порешать легкие задачи
* Порешать задачи в контексте библиотеки Numpy
* Если успеем, начать крутить данные при помощи Pandas

В то время как многие из Вас почувствуют некоторую скуку при виде темы данного семинара, остальные могут почувствовать ужас и страх перед неизвестным. В случае, если после семинара у Вас осталось ощущение, что Вы не готовы, отбросьте сомнения и немного потренируйтесь на предоставленных дополнительных материалах и/или любых открытых платформах в интернете (тысячи их), навык написания кода на питоне нарабатывается крайне быстро.

### Основные инструменты, с которыми вы столкнетесь в рамках данного курса

* [Colab](https://colab.research.google.com/#scrollTo=-Rh3-Vt9Nev9)  -  на основной странице есть несколько полезных подсказок
* [Google](https://www.google.com/) & [StackOverflow](https://stackoverflow.com/) - тут вы знаете, что делать :) Просьба не слепо копировать ответы, а **перепечатывать** код и **понимать**, что в нём происходит.
* [NumPy](https://numpy.org/doc/stable/user/) - посмотрите *quickstart* & *basics*, *array creation* и *indexing* тоже важны.
* [Pandas](https://pandas.pydata.org/docs/user_guide/) - полное описание фичей пандаса. Просто ищите нужный функционал и вычитывайте, как оно работает, если у вас не получаеся что-то сделать.
* [Matplotlib](https://matplotlib.org/stable/tutorials/index.html) & [Plotly](https://plotly.com/python/) - основные графически библиотеки. В большинстве случаев, вам хватит базового туториала + ответов с stackoverflow/google.
* [Seaborn](https://seaborn.pydata.org/tutorial/introduction.html) - надстройка над Matplotlib, в целом позволяет делать очень приятные графики.
* [Scikit-learn](https://scikit-learn.org/stable/user_guide.html) - маст-хэв библиотека любого начинающего датасаентиста и ученого. Отлично подходит для проведения исследований и обучения, но не годится к использованию в индустрии. Внутри есть юзергайд и большое количество туториалов по различным ML аспектам.
* [Pytorch](https://pytorch.org/tutorials/beginner/basics/intro.html) - основная библиотека для работы с нейронными сетями.


Форма для анонимных отзывов: [тут](https://forms.gle/sLB8NrZZoaWgYu6F7)

# Домашнее задание 1

Первое домашнее задание будет заключаться в сдаче данного ноутбука со всеми выполненными заданиями. В сданном ноутбуке должны быть сделаны как и семинарские задания, так и задания с пометкой (HW).

**Дедлайн: 16е сентября (понедельник), 19.30**

Для идентификации автора работы, пожалуйста:

* (HW) Укажите в данной ячейке ваше ФИО: Рахимов Булат Раисович
* (HW) Заполните данную анкету: TODO

## 1. Python

Содержание:
* Списки
* Словари
* Условия
* Циклы
* Функции

Вспомним несколько фактов:

* В Python присваивание переменной значения не создает копию объекта. Вместо этого, переменная просто становится ссылкой на этот объект.

* В Python есть изменяемые и неизменяемые типы. Изменяемые отличаются тем, что их содержимое можно сменить, не изменив ссылку на них. Неизменяемые объекты приходится пересоздавать, чтобы отразить изменения состояния. При этом все старые ссылки не видят это обновление, потому что указывают на старый объект.

## Списки

Первый объект нашего интереса - списки, или, как их еще называют, листы.

Список - это упорядоченная изменяемая (mutable) коллекция объектов произвольных типов.

In [ ]:
l1 = [1, 2, '3', 'word', ['word', 8, 14]]

Список - изменяемый объект. Убедимся, что это так.

In [ ]:
l2 = l1
print(l1, l2, id(l1), id(l2), sep='\n')

[1, 2, '3', 'word', ['word', 8, 14]]
[1, 2, '3', 'word', ['word', 8, 14]]
136055440024704
136055440024704


In [ ]:
l1.pop()

['word', 8, 14]

In [ ]:
print(l1, l2, id(l1), id(l2), sep='\n')

[1, 2, '3', 'word']
[1, 2, '3', 'word']
131984865403904
131984865403904


Потренируемся работать со списками, предварительно задав выборку чисел в списке `items`.

In [ ]:
items = [5, -24, 76, 44, 4, -16, 57, 0, -11,
         98, 13, 80, 16, 30, -27, -21, 78, 72]

In [ ]:
items[0]

5

**Задача 0**

Найдите произведение первого и последнего элементов списка `items`.

In [ ]:
items[0] * items[-1]

360

In [ ]:
items[-55]

IndexError: list index out of range

**Задача 1**

Найди частное суммы первых трех элементов, начиная со второго и суммы последних двух элементов.

In [ ]:
sum(items[1:4])

96

In [ ]:
s1 = items[1:4]
s2 = items[-2:]
sum(s1) / sum(s2)

0.64

**Задача 2**

Найди размах выборки (разницу между максимальным и минимальным элементами).

In [ ]:
items

[-27, -24, -21, -16, -11, 0, 4, 5, 13, 16, 30, 44, 57, 72, 76, 78, 80, 98]

In [ ]:
min(items)

-27

In [ ]:
abs(min(items) - max(items))

125

**Задача 3**

Найди среднее значение выборки.

In [ ]:
sum(items) / len(items)

26.333333333333332

**Задача 4 (HW)**

Найдите медиану.

**Задача 5 (HW)**

Удалите третье значение и найдите медиану.

**Задача 6 (HW)**

Возведите каждый элемент списка в квадрат.

In [ ]:
# Задача4
import statistics
items = [5, -24, 76, 44, 4, -16, 57, 0, -11,
         98, 13, 80, 16, 30, -27, -21, 78, 72]
median_value = statistics.median(items)
median_value

14.5

In [ ]:
# Задача 5
items = [5, -24, 76, 44, 4, -16, 57, 0, -11,
         98, 13, 80, 16, 30, -27, -21, 78, 72]
from statistics import median
items.remove(76)
print(median(items))


13


In [ ]:
# Задача 6
items = [5, -24, 76, 44, 4, -16, 57, 0, -11,
         98, 13, 80, 16, 30, -27, -21, 78, 72]
square_items = []
for item in items:
  square_items.append(item**2)
print(square_items)

[25, 576, 5776, 1936, 16, 256, 3249, 0, 121, 9604, 169, 6400, 256, 900, 729, 441, 6084, 5184]


## Словари

In [ ]:
type([1,2,3])

list

In [ ]:
{1: [1,2,3], 1: [1,2]}

{1: [1, 2]}

In [ ]:
items = {3: -2,
         4: 'value1',
         22: 2,
         10: 1.22}

**Задача 1**

Добавьте в словарик по ключу `1` значение `-20`

In [ ]:
b = [1,2,3]
b.append(4)
b

[1, 2, 3, 4]

In [ ]:
items[1] = -20

In [ ]:
items

{3: -2, 4: 'value1', 22: 2, 10: 1.22, 1: -20}

**Задача 2**

Какое значение лежит в словаре по самому маленькому ключу?

In [ ]:
items.items()

dict_items([(3, -2), (4, 'value1'), (22, 2), (10, 1.22), (1, -20)])

In [ ]:
items.values()

dict_values([-2, 'value1', 2, 1.22, -20])

In [ ]:
items.keys()

dict_keys([3, 4, 22, 10, 1])

In [ ]:
min(items.keys())

1

In [ ]:
items[min(items.keys())]

-20

**Задача 3**

Удалите ключ из задачи 2 и заново решите её.

In [ ]:
items.pop(1)

-20

In [ ]:
min(items.keys())

3

In [ ]:
items[min(items.keys())]

-2

In [ ]:
dict_1 = {1: 10, 2: 20}
dict_2 = {3: 30, 4: 40}
dict_3 = {3: 50, 6: 60}

**Задача 4**

Объедините три словаря в один.

In [ ]:
dict_1.update(dict_2)

In [ ]:
dict_1.update(dict_3)
dict_1

{1: 10, 2: 20, 3: 50, 4: 40, 6: 60}

**Задача 5**

Замените все значения словаря на их квадраты.

In [ ]:
dict_1 = {1: 10, 2: 20}
dict_2 = {3: 30, 4: 40}
dict_3 = {3: 50, 6: 60}
dict_1.update(dict_2)
dict_1.update(dict_3)
new_dictionary = {}
for key in dict_1:
  new_dictionary[key] = dict_1[key]**2
print(new_dictionary)




{1: 100, 2: 400, 3: 2500, 4: 1600, 6: 3600}


## Условия

Синтаксис:
```
if условие:
    что делать, если оно выполнено
elif условие:
    что делать, если оно выполнено
else:
    что делать, если не выполнилось ни одно условие выше
```
Всё, что происходит внутри условия, отделяется отступом.

**Задача 1**

Заведите переменную year и проверьте, является ли введеный год високосным.

Год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [ ]:
year = 2020

if year % 4 == 0 and year % 100 != 0:
  print('Високосный')
elif year % 400 == 0:
  print('Високосный')
else:
  print('Обычный')

Високосный


## Циклы

In [ ]:
while tmp != 0:
  ...
  tmp -= 1

Синтаксис:
```
for i in диапазон_изменений_i:
    команды
```
Все, что происходит внутри цикла, отделяется отступом.

**Задача 1**

Напиши программу для вывода картинки заданной глубины (используйте вложенные циклы).
```
*
**
***
****
*****
****
***
**
*
```

In [ ]:
for i in range (1, 6):
  for j in range(i):
    print('*', end = "")
  print()

for i in range (4, 0, -1):
  for j in range(i):
    print('*', end = '')
  print()

*
**
***
****
*****
****
***
**
*


## Функции

Синтаксис:

```
def название функции(список аргументов):
    команды
    return результат выполнения функции
```

То, что происходит внутри функции отделяется отступом.

In [ ]:
def hello(name, surname='Иванов'):

**Задача 1**

Напишите функцию, принимающую на вход строку, и разворачивающую её вспять.

In [ ]:
def inverse(string):
  return(string[::-1])
inverse("hello")

'olleh'

**Задача 2 (HW)**

Напишите функцию, которая принимает на вход число n, числа a, b и генерирует случайных числе с отрезка от $a$ до $b$.

In [ ]:
import random
def generate(n, a, b):
  return([random.randint(a,b) for i in range(n)])
generate(5, 1, 10)

[1, 7, 10, 8, 10]

## 2. Numpy

В задачах анализа данных часто используются многомерные массивы. В частности, выборка обычно имеет вид матрицы размера
$N \times d$, где
$N$ — количество объектов, а
$d$ — признаков.

Но чистый Python довольно неудобный и слишком медленный для подобных задач. Конечно, можно представить матрицу в виде «списка списков», но с первого раза без ошибок такой объект сложно даже создать. Например, так делать не надо:

In [ ]:
vector = [0, 0, 0, 0, 0]  # Создаём строчку
matrix = 5 * [vector]     # Создаём список из строчек
matrix

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [ ]:
matrix[0][0] = 1  # Хотим изменить один элемент
matrix            # А получилось что-то не то...

[[1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0]]

Но даже если мы сможем корректно создать матрицу в виде списка списков, функции для работы с ней придётся писать самостоятельно. Они будут содержать циклы языка Python и, как следствие, медленно работать.

Поэтому естественно было придумать библиотеку для работы с многомерными массивами. Такой библиотекой стала библиотека NumPy.

NumPy — библиотека языка Python, позволяющая удобно работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении.

## Основной класс - `ndarray`

Основной класс в `numpy` - `ndarray`, многомерный массив.

`ndarray` имеет все преимущества массива, а также обеспечивает быструю обработку без использования относительно медленных циклов Python.

Каждый подобный массив имеет несколько измерений или осей — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси и т.д.

## Импорт `numpy`

`import numpy as np`

`np` - синоним имени модуля, пространство имен, ссылка для доступа к компонентам модуля


In [ ]:
import numpy as np

## Способы создания массива

- `np.array(obj, dtype, ...)` - преобразование из списка, кортежа, генератора, другого массива, ...
    - `obj` - объект, который нужно преобразовать
    - `dtype` - тип элемента массива
- функции `numpy`
- операции с массивами

In [ ]:
# одномерный массив из списка и кортежа
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
# получили объект типа numpy.ndarray
type(x)

numpy.ndarray

In [ ]:
for i in range(13):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# преобразование из генератора
np.array(range(13))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# преобразование из генератора списка
np.array([x**2 for x in range(13)])

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

## Типы элементов массива

В отличие от чистого Python`а с динамической типизацией в NumPy типизация статическая, как в C/C++. Поэтому у каждого многомерного массива должен быть тип элементов, который обычно можно указать явно с помощью параметра dtype. К тому же, все элементы в массиве должны быть одного типа.

Встроенные типы `Python`:

- `int`, `bool`, `float`, `complex`, `str`, ...

Типы `numpy`:

- `np.int0`, `np.int8`, `np.int16`, `np.int32`, `np.int64`
- `np.float`, `np.float16`, `np.float32`, `np.float64`
- `np.complex`, `np.complex64`, `np.complex128`

Также можно задать тип, эквивалентный `struct` в языке Си, т.е. упорядоченный набор из разнотипных элементов, занимающих жестко фиксированное количество байт.


Здесь без явного указания массив будет состоять из целых чисел:

In [ ]:
np.array([[1, 2, 3], [1, 2, 3]], dtype=float)

array([[1., 2., 3.],
       [1., 2., 3.]])

Доступна и бóльшая экзотика. Например, можно потребовать, чтобы массив состоял из 16-битных чисел с плавающей точкой. Но в курсе нам будет достаточно простых типов int, float, bool.

In [ ]:
np.array([[1, 2, 3], [1, 2, 3]], dtype=np.float16)

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float16)

Ещё можно создавать массив определённого размера из нулей:

In [ ]:
arr = np.zeros((3, 4), dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

... единиц:

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

... вообще из чего угодно:



In [ ]:
np.full((3, 4), 5, dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

... а память просто выделять, не инициализируя:

In [ ]:
np.empty((5, 4))

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

In [ ]:
# массив с элементами разных типов
for dtype in (int, float, bool):
    print('%r' % np.array([0, 1, 2, 3], dtype=dtype))

array([0, 1, 2, 3])
array([0., 1., 2., 3.])
array([False,  True,  True,  True])


In [ ]:
# массив с элементами разных типов
for dtype in (np.int0, np.int8, np.int16, np.int32):
    arr = np.array([0, 1, 2, 3], dtype=dtype)
    print(dtype)
    print('%r' % arr)
    print('memory size:', arr.nbytes, end='\n'*2)

<class 'numpy.int64'>
array([0, 1, 2, 3])
memory size: 32

<class 'numpy.int8'>
array([0, 1, 2, 3], dtype=int8)
memory size: 4

<class 'numpy.int16'>
array([0, 1, 2, 3], dtype=int16)
memory size: 8

<class 'numpy.int32'>
array([0, 1, 2, 3], dtype=int32)
memory size: 16



<ipython-input-4-31ce702e982f>:2: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  for dtype in (np.int0, np.int8, np.int16, np.int32):


## Атрибуты массива

- `arr.shape` - размеры массива = его форма (кортеж)
- `arr.size` - количество элементов массива
- `arr.dtype` - тип элемента массива
- `arr.ndim` - количество измерений массива (целое число > 0)
- `arr.strides` - шаги в байтах для перехода к следующему элементу измерения (кортеж)
- `arr.nbytes` - размер занимаемой памяти в байтах

In [ ]:
arr = np.array(range(12))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.ndim, arr.size, arr.dtype, arr.shape, arr.strides, arr.nbytes

(1, 12, dtype('int64'), (12,), (8,), 96)

Изменять «размерность» массива можно с помощью метода reshape. Для этого, конечно, произведение размерностей должно равняться количеству элементов массива.

In [ ]:
arr = arr.reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Вместо количества элементов по одной «размерности» можно указать -1, и тогда NumPy сам посчитает это число:

In [ ]:
arr = arr.reshape(4, -1)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Ещё одна полезная функция — np.arange(...), которая по сути эквивалентна запуску np.array(range(...)).

Полученный одномерный массив удобно превращать в матрицу с помощью reshape:

In [ ]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

К тому же, можно генерировать матрицы из вероятностных распределений.

Вот матрица размера $3 \times 4$ из $\mathcal{N}(0,10)$:

In [ ]:
np.random.normal(0, np.sqrt(10), (3, 4))

array([[ 0.99227948,  0.02679473,  9.33148704, -3.59295203],
       [-0.71283148, -2.45207896, -2.56377464,  3.51006714],
       [-4.04890276, -1.52636615,  3.47772214, -5.30978698]])

**Задание 1 (HW)**

Создать массивы типа `ndarray` и вывести на экран:
- содержимое
- форму
- размер занимаемой памяти

1. одномерный массив, содержащий действительные числа $\pi, \frac{\pi}{2}, \frac{\pi}{4}, \frac{\pi}{9}, \frac{\pi}{16}, ..., \frac{\pi}{1024}$

2. одномерный массив, содержащий константу `True`, если число делится на 5, иначе - `False` для чисел 10, ..., 100.


In [ ]:
# 1 пункт
from math import pi
import numpy as np
power = np.arange(0, 11, 1)
pi_power = [pi /(2 ** n) for n in power]
arr_pi_power = np.array(pi_power)
print(arr_pi_power)
print(arr_pi_power.shape)
print(arr_pi_power.nbytes)

[3.14159265e+00 1.57079633e+00 7.85398163e-01 3.92699082e-01
 1.96349541e-01 9.81747704e-02 4.90873852e-02 2.45436926e-02
 1.22718463e-02 6.13592315e-03 3.06796158e-03]
(11,)
88


In [ ]:
#2 пункт
arr_const = np.array([i % 5 == 0 for i in range(10,101)])
print(arr_const)
print(arr_const.shape)
print(arr_const.nbytes)

[ True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True]
(91,)
91


**Задание 2 (HW)**
1. Сгенерировать последовательность из 100 элементов: `[1.18, 3.27, ...]`

2. Создать двумерный массив из 100 псевдослучайных чисел, равномерно распределенных на полуинтервале $[\pi, 10\pi)$

3. Преобразовать полученный массив так, чтобы элементы стали целочисленными

4. Из массива `[0, 1, ..., 99]` случайным образом выбрать 10 элементов


In [ ]:
# Генерация последовательности из 100 элементов [1.18, 3.27, ...]
generate_arr = np.arange(1.18, 101.18, 2.09)
print(generate_arr)

#Пункт 2
random_arr = np.random.uniform(pi, 10 * pi, (10, 10))
print(random_arr)

#Пункт 3
int_random_arr = np.array(random_arr, dtype = int)
print(int_random_arr)

#Пункт 4
new_arr = np.arange(0, 100)
new_random_arr = np.random.choice(new_arr, size=10, replace = False)
print(new_random_arr)

[ 1.18  3.27  5.36  7.45  9.54 11.63 13.72 15.81 17.9  19.99 22.08 24.17
 26.26 28.35 30.44 32.53 34.62 36.71 38.8  40.89 42.98 45.07 47.16 49.25
 51.34 53.43 55.52 57.61 59.7  61.79 63.88 65.97 68.06 70.15 72.24 74.33
 76.42 78.51 80.6  82.69 84.78 86.87 88.96 91.05 93.14 95.23 97.32 99.41]
[[29.99914797 26.93829034 14.12035486  8.62616604  3.89841023 10.02270103
  17.8954391  14.09005467  7.51135343  6.51962118]
 [23.80264922 22.66873064 13.38481506  4.61760719 28.89925432  6.97866836
  20.62960897 22.15191326  5.04209636 20.19978159]
 [14.41700162 15.74745131 14.68726505 31.02613439 14.21239197 16.36920429
  13.61645824 28.06971547 10.84166265  9.05294152]
 [20.92262442 21.00583063 31.27326209 28.23263206 25.69655209 11.69763633
  31.33882851 14.23138728 11.55221889  5.75045579]
 [26.24076911 28.61862321  6.59850051 26.20797473  4.34209618 24.06571298
  23.79466096  5.96785813 23.42460785 15.88276982]
 [14.66391756  5.90076293 12.73897044 25.68224679  4.58596803 20.1725145
  21.8640

**Задание 3 (HW)**

Реализуйте функцию, принимающую на вход массив целых неотрицательных чисел `nums` и возвращающую самый частый элемент массива.

In [ ]:
def most_frequent(nums):
  most_frequent_nums = np.argmax(np.bincount(nums))
  return(most_frequent_nums)

some_arr = np.array([1, 1, 1, 3, 3, 7, 10, 100, 40])
most_frequent(some_arr)

1